#!/usr/bin/env python3
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from project_setup.cli import update_main
update_main(root=Path(__file__).resolve().parent.parent)
